# Generated by Django 5.0.4 on 2024-05-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0002_hasband_women_hasband"),
    ]

    operations = [
        migrations.AddField(
            model_name="hasband",
            name="m_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
