# Generated by Django 5.0.4 on 2024-05-07 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0003_hasband_m_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорії", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterModelOptions(
            name="women",
            options={
                "verbose_name": "Відомі жінки",
                "verbose_name_plural": "Відомі жінки",
            },
        ),
        migrations.RemoveIndex(
            model_name="women",
            name="women_women_time_cr_9f33c2_idx",
        ),
        migrations.AlterField(
            model_name="women",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="Мінімум 5 символів"
                    ),
                    django.core.validators.MaxLengthValidator(
                        100, message="Мінімум 100 символів"
                    ),
                ],
            ),
        ),
    ]
