# Generated by Django 5.0.4 on 2024-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0005_uploadfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d",
                verbose_name="Фото",
            ),
        ),
    ]
